import { describe, it, expect } from "vitest";
import { readLocalCommandTurn } from "./localCommandTurns";

describe("readLocalCommandTurn", () => {
  it("ignores ordinary user text", () => {
    expect(readLocalCommandTurn("run the tests")).toBeNull();
  });

  it("ignores text that merely mentions a tag", () => {
    // The block has to *be* the message, not appear in it, or a question about
    // the tag would vanish from the transcript.
    expect(
      readLocalCommandTurn(
        "why does <local-command-stdout>x</local-command-stdout> show up?",
      ),
    ).toBeNull();
  });

  it("turns an invocation back into the command as typed", () => {
    const turn = readLocalCommandTurn(
      "<command-name>/compact</command-name>\n            <command-message>compact</command-message>\n            <command-args></command-args>",
    );

    // Reassembled with the slash, which is also what the transcript's command
    // highlighting matches on.
    expect(turn).toEqual({ kind: "invocation", text: "/compact" });
  });

  it("keeps the arguments a command was given", () => {
    const turn = readLocalCommandTurn(
      "<command-name>/rename</command-name><command-message>rename</command-message><command-args>New title</command-args>",
    );

    expect(turn).toEqual({ kind: "invocation", text: "/rename New title" });
  });

  it("recognises the caveat aimed at the model", () => {
    expect(
      readLocalCommandTurn(
        "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>",
      ),
    ).toEqual({ kind: "caveat" });
  });

  it("marks a compaction acknowledgement as redundant", () => {
    expect(
      readLocalCommandTurn(
        "<local-command-stdout>Compacted </local-command-stdout>",
      ),
    ).toEqual({ kind: "output", text: "Compacted", isRedundant: true });
  });

  it("marks an empty block as redundant", () => {
    const turn = readLocalCommandTurn(
      "<local-command-stdout></local-command-stdout>",
    );

    expect(turn).toMatchObject({ kind: "output", isRedundant: true });
  });

  it("keeps output that carries the command's actual answer", () => {
    // /cost and friends put their whole result here; dropping every block
    // would throw that away along with the noise.
    expect(
      readLocalCommandTurn(
        "<local-command-stdout>Total cost: $0.42\nDuration: 3m</local-command-stdout>",
      ),
    ).toEqual({
      kind: "output",
      text: "Total cost: $0.42\nDuration: 3m",
      isRedundant: false,
    });
  });
});
